// Fixed allowlist: no auth tables, credentials, or private.study_graph_config.
// Order follows foreign keys. Extend together with the backup version when the schema changes.
export const backupTables = [
  { name: "public.review_state", keys: ["item_id"], columns: [
    {"name":"item_id","type":"text"},
    {"name":"item_kind","type":"text"},
    {"name":"last_grade","type":"text"},
    {"name":"repetitions","type":"int4"},
    {"name":"interval_days","type":"int4"},
    {"name":"last_reviewed_at","type":"timestamptz"},
    {"name":"due_at","type":"timestamptz"},
    {"name":"updated_at","type":"timestamptz"},
  ] },
  { name: "public.review_attempts", keys: ["id"], columns: [
    {"name":"id","type":"int8"},
    {"name":"item_id","type":"text"},
    {"name":"item_kind","type":"text"},
    {"name":"grade","type":"text"},
    {"name":"previous_interval_days","type":"int4"},
    {"name":"interval_days","type":"int4"},
    {"name":"reviewed_at","type":"timestamptz"},
    {"name":"due_at","type":"timestamptz"},
    {"name":"exercise_id","type":"text"},
    {"name":"answer_type","type":"text"},
    {"name":"answer_text","type":"text"},
    {"name":"is_correct","type":"bool"},
    {"name":"response_ms","type":"int4"},
    {"name":"used_hint","type":"bool"},
  ] },
  { name: "private.content_releases", keys: ["release_id"], columns: [
    {"name":"release_id","type":"text"},
    {"name":"manifest_schema_version","type":"int4"},
    {"name":"manifest_hash","type":"text"},
    {"name":"manifest","type":"jsonb"},
    {"name":"source_git_sha","type":"text"},
    {"name":"created_at","type":"timestamptz"},
  ] },
  { name: "private.exercise_revisions", keys: ["revision_id"], columns: [
    {"name":"revision_id","type":"uuid"},
    {"name":"project_id","type":"text"},
    {"name":"exercise_id","type":"text"},
    {"name":"exercise_version","type":"int4"},
    {"name":"content_hash","type":"text"},
    {"name":"canonicalization_version","type":"int4"},
    {"name":"canonical_payload","type":"text"},
    {"name":"payload","type":"jsonb"},
    {"name":"objective_id","type":"text"},
    {"name":"created_at","type":"timestamptz"},
  ] },
  { name: "private.content_release_entries", keys: ["release_id","revision_id"], columns: [
    {"name":"release_id","type":"text"},
    {"name":"revision_id","type":"uuid"},
  ] },
  { name: "private.objective_definitions", keys: ["project_id","objective_id","objective_version"], columns: [
    {"name":"project_id","type":"text"},
    {"name":"objective_id","type":"text"},
    {"name":"objective_version","type":"int4"},
    {"name":"canonicalization_version","type":"int4"},
    {"name":"canonical_payload","type":"text"},
    {"name":"content_hash","type":"text"},
    {"name":"payload","type":"jsonb"},
    {"name":"created_at","type":"timestamptz"},
  ] },
  { name: "private.exercise_objective_bindings", keys: ["binding_id"], columns: [
    {"name":"binding_id","type":"uuid"},
    {"name":"revision_id","type":"uuid"},
    {"name":"project_id","type":"text"},
    {"name":"objective_id","type":"text"},
    {"name":"objective_version","type":"int4"},
    {"name":"evidence_use","type":"text"},
    {"name":"created_at","type":"timestamptz"},
  ] },
  { name: "private.scope_knowledge_snapshots", keys: ["snapshot_id"], columns: [
    {"name":"snapshot_id","type":"uuid"},
    {"name":"project_id","type":"text"},
    {"name":"generation","type":"int8"},
    {"name":"schema_version","type":"int4"},
    {"name":"source_read_started_at","type":"timestamptz"},
    {"name":"source_read_completed_at","type":"timestamptz"},
    {"name":"published_at","type":"timestamptz"},
    {"name":"valid_until","type":"timestamptz"},
    {"name":"scope_policy_version","type":"text"},
    {"name":"knowledge_projection_version","type":"text"},
    {"name":"source_evidence","type":"jsonb"},
    {"name":"scope_decisions","type":"jsonb"},
    {"name":"knowledge_projection","type":"jsonb"},
    {"name":"content_hash","type":"text"},
    {"name":"created_at","type":"timestamptz"},
  ] },
  { name: "private.project_snapshot_sync_state", keys: ["project_id"], columns: [
    {"name":"project_id","type":"text"},
    {"name":"current_snapshot_id","type":"uuid"},
    {"name":"current_generation","type":"int8"},
    {"name":"next_generation","type":"int8"},
    {"name":"active_run_id","type":"uuid"},
    {"name":"active_generation","type":"int8"},
    {"name":"active_started_at","type":"timestamptz"},
    {"name":"active_lease_until","type":"timestamptz"},
    {"name":"last_attempted_at","type":"timestamptz"},
    {"name":"last_succeeded_at","type":"timestamptz"},
    {"name":"last_failed_at","type":"timestamptz"},
    {"name":"last_error_code","type":"text"},
    {"name":"last_error_detail","type":"text"},
    {"name":"updated_at","type":"timestamptz"},
  ] },
  { name: "private.exercise_instances", keys: ["instance_id"], columns: [
    {"name":"instance_id","type":"uuid"},
    {"name":"learner_id","type":"uuid"},
    {"name":"release_id","type":"text"},
    {"name":"revision_id","type":"uuid"},
    {"name":"presentation","type":"jsonb"},
    {"name":"presentation_hash","type":"text"},
    {"name":"renderer_version","type":"text"},
    {"name":"adapter_version","type":"text"},
    {"name":"locale","type":"text"},
    {"name":"scope_evidence","type":"jsonb"},
    {"name":"knowledge_binding","type":"jsonb"},
    {"name":"legacy_item_id","type":"text"},
    {"name":"legacy_item_kind","type":"text"},
    {"name":"legacy_exercise_id","type":"text"},
    {"name":"srs_target","type":"text"},
    {"name":"srs_epoch","type":"text"},
    {"name":"issued_at","type":"timestamptz"},
  ] },
  { name: "private.instance_objective_bindings", keys: ["instance_id","project_id","objective_id","objective_version","srs_epoch","evidence_use"], columns: [
    {"name":"instance_id","type":"uuid"},
    {"name":"project_id","type":"text"},
    {"name":"objective_id","type":"text"},
    {"name":"objective_version","type":"int4"},
    {"name":"srs_epoch","type":"int4"},
    {"name":"evidence_use","type":"text"},
    {"name":"created_at","type":"timestamptz"},
    {"name":"scheduling_context_version","type":"int4"},
    {"name":"opportunity_kind","type":"text"},
    {"name":"expected_state_revision","type":"int8"},
    {"name":"grade_policy_version","type":"text"},
    {"name":"activation_policy_version","type":"text"},
    {"name":"issued_at","type":"timestamptz"},
    {"name":"expires_at","type":"timestamptz"},
    {"name":"due_at_observed","type":"timestamptz"},
  ] },
  { name: "private.exercise_attempts", keys: ["attempt_id"], columns: [
    {"name":"attempt_id","type":"uuid"},
    {"name":"instance_id","type":"uuid"},
    {"name":"learner_id","type":"uuid"},
    {"name":"request_hash","type":"text"},
    {"name":"raw_answer","type":"jsonb"},
    {"name":"normalized_answer","type":"jsonb"},
    {"name":"grading_status","type":"text"},
    {"name":"grading_authority","type":"text"},
    {"name":"grading_strategy_id","type":"text"},
    {"name":"grading_strategy_version","type":"int4"},
    {"name":"normalizer_version","type":"text"},
    {"name":"is_correct","type":"bool"},
    {"name":"self_evaluation","type":"text"},
    {"name":"effective_srs_grade","type":"text"},
    {"name":"response_ms","type":"int4"},
    {"name":"used_hint","type":"bool"},
    {"name":"scope_accepted","type":"bool"},
    {"name":"srs_applied","type":"bool"},
    {"name":"srs_reason","type":"text"},
    {"name":"scheduler_version","type":"text"},
    {"name":"review_state_before","type":"jsonb"},
    {"name":"review_state_after","type":"jsonb"},
    {"name":"legacy_review_attempt_id","type":"int8"},
    {"name":"receipt","type":"jsonb"},
    {"name":"submitted_at","type":"timestamptz"},
  ] },
  { name: "private.objective_srs_applications", keys: ["application_id"], columns: [
    {"name":"application_id","type":"uuid"},
    {"name":"attempt_id","type":"uuid"},
    {"name":"instance_id","type":"uuid"},
    {"name":"learner_id","type":"uuid"},
    {"name":"project_id","type":"text"},
    {"name":"objective_id","type":"text"},
    {"name":"objective_version","type":"int4"},
    {"name":"srs_epoch","type":"int4"},
    {"name":"evidence_use","type":"text"},
    {"name":"applied","type":"bool"},
    {"name":"reason","type":"text"},
    {"name":"effective_grade","type":"text"},
    {"name":"scheduler_version","type":"text"},
    {"name":"state_before","type":"jsonb"},
    {"name":"state_after","type":"jsonb"},
    {"name":"receipt","type":"jsonb"},
    {"name":"created_at","type":"timestamptz"},
  ] },
  { name: "private.objective_review_state", keys: ["learner_id","project_id","objective_id","srs_epoch"], columns: [
    {"name":"learner_id","type":"uuid"},
    {"name":"project_id","type":"text"},
    {"name":"objective_id","type":"text"},
    {"name":"srs_epoch","type":"int4"},
    {"name":"last_grade","type":"text"},
    {"name":"repetitions","type":"int4"},
    {"name":"interval_days","type":"int4"},
    {"name":"last_reviewed_at","type":"timestamptz"},
    {"name":"due_at","type":"timestamptz"},
    {"name":"scheduler_version","type":"text"},
    {"name":"state_revision","type":"int8"},
    {"name":"last_application_id","type":"uuid"},
    {"name":"created_at","type":"timestamptz"},
    {"name":"updated_at","type":"timestamptz"},
  ] },
  { name: "private.objective_srs_opportunities", keys: ["opportunity_id"], columns: [
    {"name":"opportunity_id","type":"uuid"},
    {"name":"instance_id","type":"uuid"},
    {"name":"learner_id","type":"uuid"},
    {"name":"project_id","type":"text"},
    {"name":"objective_id","type":"text"},
    {"name":"objective_version","type":"int4"},
    {"name":"srs_epoch","type":"int4"},
    {"name":"evidence_use","type":"text"},
    {"name":"status","type":"text"},
    {"name":"terminal_reason","type":"text"},
    {"name":"created_at","type":"timestamptz"},
    {"name":"terminalized_at","type":"timestamptz"},
  ] },
  { name: "private.offline_instance_issuance_requests", keys: ["request_id"], columns: [
    {"name":"request_id","type":"uuid"},
    {"name":"learner_id","type":"uuid"},
    {"name":"project_id","type":"text"},
    {"name":"device_id","type":"uuid"},
    {"name":"instance_id","type":"uuid"},
    {"name":"snapshot_id","type":"uuid"},
    {"name":"snapshot_generation","type":"int8"},
    {"name":"assets","type":"jsonb"},
    {"name":"feedback","type":"jsonb"},
    {"name":"created_at","type":"timestamptz"},
  ] },
];
