create extension if not exists pgcrypto with schema extensions;

create schema if not exists private;

create table if not exists private.study_graph_config (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

revoke all on schema private from public;
revoke all on all tables in schema private from public, anon, authenticated;

create table if not exists public.review_state (
  item_id text primary key,
  item_kind text not null check (item_kind in ('character', 'mistake')),
  last_grade text not null check (last_grade in ('again', 'hard', 'good', 'easy')),
  repetitions integer not null default 0 check (repetitions >= 0),
  interval_days integer not null default 0 check (interval_days >= 0),
  last_reviewed_at timestamptz not null,
  due_at timestamptz not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.review_attempts (
  id bigint generated by default as identity primary key,
  item_id text not null,
  item_kind text not null check (item_kind in ('character', 'mistake')),
  grade text not null check (grade in ('again', 'hard', 'good', 'easy')),
  previous_interval_days integer not null default 0 check (previous_interval_days >= 0),
  interval_days integer not null default 0 check (interval_days >= 0),
  reviewed_at timestamptz not null default now(),
  due_at timestamptz not null
);

create index if not exists review_state_due_at_idx on public.review_state (due_at);
create index if not exists review_attempts_item_reviewed_idx on public.review_attempts (item_id, reviewed_at desc);

alter table public.review_state enable row level security;
alter table public.review_attempts enable row level security;

revoke all on public.review_state from public, anon, authenticated;
revoke all on public.review_attempts from public, anon, authenticated;

create or replace function private.study_graph_token_valid(p_token text)
returns boolean
language sql
stable
security definer
set search_path = private, extensions
as $$
  select exists (
    select 1
    from private.study_graph_config
    where key = 'app_token_sha256'
      and value = encode(digest(coalesce(p_token, ''), 'sha256'), 'hex')
  );
$$;

revoke all on function private.study_graph_token_valid(text) from public, anon, authenticated;

create or replace function public.study_graph_review_states(p_token text)
returns table (
  item_id text,
  item_kind text,
  last_grade text,
  repetitions integer,
  interval_days integer,
  last_reviewed_at timestamptz,
  due_at timestamptz
)
language plpgsql
security definer
set search_path = public, private, extensions
as $$
begin
  if not private.study_graph_token_valid(p_token) then
    raise exception using errcode = '42501', message = 'unauthorized';
  end if;

  return query
  select
    rs.item_id,
    rs.item_kind,
    rs.last_grade,
    rs.repetitions,
    rs.interval_days,
    rs.last_reviewed_at,
    rs.due_at
  from public.review_state rs;
end;
$$;

create or replace function public.study_graph_record_review(
  p_token text,
  p_item_id text,
  p_item_kind text,
  p_grade text
)
returns table (
  due_at timestamptz,
  interval_days integer,
  repetitions integer
)
language plpgsql
security definer
set search_path = public, private, extensions
as $$
declare
  v_now timestamptz := now();
  v_previous_interval integer := 0;
  v_previous_repetitions integer := 0;
  v_interval integer := 0;
  v_repetitions integer := 0;
  v_due timestamptz;
begin
  if not private.study_graph_token_valid(p_token) then
    raise exception using errcode = '42501', message = 'unauthorized';
  end if;

  if p_item_kind not in ('character', 'mistake') then
    raise exception using errcode = '22023', message = 'invalid item kind';
  end if;

  if p_grade not in ('again', 'hard', 'good', 'easy') then
    raise exception using errcode = '22023', message = 'invalid grade';
  end if;

  select rs.interval_days, rs.repetitions
    into v_previous_interval, v_previous_repetitions
  from public.review_state rs
  where rs.item_id = p_item_id
  for update;

  v_previous_interval := coalesce(v_previous_interval, 0);
  v_previous_repetitions := coalesce(v_previous_repetitions, 0);

  case p_grade
    when 'again' then
      v_interval := 0;
      v_repetitions := 0;
      v_due := v_now + interval '10 minutes';
    when 'hard' then
      v_interval := case
        when v_previous_interval = 0 then 1
        else greatest(1, ceil(v_previous_interval * 1.2)::integer)
      end;
      v_repetitions := v_previous_repetitions + 1;
      v_due := v_now + make_interval(days => v_interval);
    when 'good' then
      v_interval := case
        when v_previous_interval = 0 then 2
        else greatest(2, round(v_previous_interval * 2.2)::integer)
      end;
      v_repetitions := v_previous_repetitions + 1;
      v_due := v_now + make_interval(days => v_interval);
    when 'easy' then
      v_interval := case
        when v_previous_interval = 0 then 5
        else greatest(5, round(v_previous_interval * 3.2)::integer)
      end;
      v_repetitions := v_previous_repetitions + 1;
      v_due := v_now + make_interval(days => v_interval);
  end case;

  insert into public.review_attempts (
    item_id,
    item_kind,
    grade,
    previous_interval_days,
    interval_days,
    reviewed_at,
    due_at
  ) values (
    p_item_id,
    p_item_kind,
    p_grade,
    v_previous_interval,
    v_interval,
    v_now,
    v_due
  );

  insert into public.review_state (
    item_id,
    item_kind,
    last_grade,
    repetitions,
    interval_days,
    last_reviewed_at,
    due_at,
    updated_at
  ) values (
    p_item_id,
    p_item_kind,
    p_grade,
    v_repetitions,
    v_interval,
    v_now,
    v_due,
    v_now
  )
  on conflict (item_id) do update set
    item_kind = excluded.item_kind,
    last_grade = excluded.last_grade,
    repetitions = excluded.repetitions,
    interval_days = excluded.interval_days,
    last_reviewed_at = excluded.last_reviewed_at,
    due_at = excluded.due_at,
    updated_at = excluded.updated_at;

  return query select v_due, v_interval, v_repetitions;
end;
$$;

revoke all on function public.study_graph_review_states(text) from public;
revoke all on function public.study_graph_record_review(text, text, text, text) from public;
grant execute on function public.study_graph_review_states(text) to anon, authenticated;
grant execute on function public.study_graph_record_review(text, text, text, text) to anon, authenticated;

comment on table public.review_state is 'Current spaced-review scheduling state for Study Graph. Notion remains the source of knowledge content.';
comment on table public.review_attempts is 'Append-only Study Graph review attempt history.';
comment on function public.study_graph_record_review(text, text, text, text) is 'Records one review and advances a lightweight replaceable scheduling policy.';
